version: '3.8'

services:
  postgres_helpcentre:
    image: postgres:15
    container_name: postgres_helpcentre
    restart: always
    environment:
      POSTGRES_USER: helpcentre_user
      POSTGRES_PASSWORD: helpcentre_pass
      POSTGRES_DB: helpcentre_db
    ports:
      - "5432:5690"
    volumes:
      - postgres_helpcentre_data:/var/lib/postgresql/data
    networks:
      - proxy_hostinger-network

  indexer:
    image: beijuka/tb-chatbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: none
    networks:
      - proxy_hostinger-network

  api:
    image: beijuka/tb-chatbot:latest
    depends_on:
      - indexer
      - postgres_helpcentre
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy_hostinger-network

volumes:
  postgres_helpcentre_data:

networks:
  proxy_hostinger-network:
    external: true
